/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package panels;

import constants.ColorsTheme;
import constants.FontsTheme;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import dialogs.NewReportDialog;

/**
 *
 * 
 */
public class ReportsPanel extends JPanel implements ActionListener{
    
    private JPanel pnlMiddle, pnlPatient, pnlBilling, pnlLab, pnlPharmacy, cardPanel, TopPanel;
    private JLabel lblDetails, lblReports, lblTitle, lblValue, lblSubtitle, lblHead;
    private JButton btnAdd;
    private JTable tblReport;
    private JScrollPane scrollReport;
    
    
    public ReportsPanel() {
        setLayout(null);
        setBackground(ColorsTheme.Middle_Panel);
        
        pnlMiddle = new JPanel();
        pnlMiddle.setLayout(null);
        pnlMiddle.setBounds(70, 300, 1500, 500);
        pnlMiddle.setBackground(ColorsTheme.Main_Card);
        add(pnlMiddle);
        

        lblReports = new JLabel("Reports");
        lblReports.setBounds(30, 30, 500, 40);
        lblReports.setFont(FontsTheme.Bold_Texts);
        lblReports.setForeground(ColorsTheme.Text_Black);
        add(lblReports);

        lblDetails = new JLabel("Generate and view hospital reports.");
        lblDetails.setBounds(30, 70, 500, 40);
        lblDetails.setFont(FontsTheme.Plain_Texts);
        lblDetails.setForeground(ColorsTheme.Text_Gray);
        add(lblDetails);
        
        btnAdd = new JButton("+  Generate Report");
        btnAdd.setBounds(1280, 40, 250, 50); 
        btnAdd.setFont(FontsTheme.Buttons);
        btnAdd.setBackground(ColorsTheme.Add_Confirm);
        btnAdd.setForeground(ColorsTheme.Text_White);
        add(btnAdd);
        
        
        
        pnlPatient = createCard("Patient Reports", "24", "Records Summary", ColorsTheme.Blue);
        pnlPatient.setBounds(70, 130, 350, 140);
        add(pnlPatient);
        
        
        pnlBilling = createCard("Billing Reports", "18", "Revenue and Invoices", ColorsTheme.Green);
        pnlBilling.setBounds(450, 130, 350, 140);
        add(pnlBilling);
        
       
        pnlLab = createCard("Lab Reports", "32", "Test Results", ColorsTheme.Red);
        pnlLab.setBounds(830, 130, 350, 140);
        add(pnlLab);
        
        
        pnlPharmacy = createCard("Pharmacy Reports", "15", "Inventory movement", ColorsTheme.Yellow);
        pnlPharmacy.setBounds(1210, 130, 350, 140);
        add(pnlPharmacy);
        
        
        
        
        //Table
        String[] columns = {"Report Name", "Type", "Generated By", "Date Generated", "Status", "Actions"};
        Object[][] data = {
                {"Daily Patient Census", "Patient", "Admin", "May 12, 2026", "Ready", " "},
                {"Monthly Revenue Summary", "Billing", "Cashier", "May 11, 2026", "Ready", " "},
                {"Laboratory Test Summary", "Laboratory", "Lab Staff", "May 11, 2026", "Processing", " "},
                {"Low Stock Inventory", "Pharmacy", "Pharmacist", "May 10, 2026", "Ready", " "},
                {"Bed Occupancy Report", "Bed Management", "Nurse Station", "May 10, 2026", "Ready", " "},
                {"Emergency Case Summary", "Emergency", "ER Staff", "May 09, 2026", "Failed", " "},
                {"Appointment Summary", "Appointments", "Reception", "May 09, 2026", "Ready", " "}
        };
        
        
        tblReport = new JTable (data, columns);
        tblReport.getTableHeader().setFont(FontsTheme.Title_Texts);
        tblReport.setFont(FontsTheme.Info_Texts);
        tblReport.setRowHeight(50);
        tblReport.setDefaultEditor(Object.class, null);
        tblReport.getTableHeader().setReorderingAllowed(false);
        tblReport.getTableHeader().setBackground(ColorsTheme.Header); 
        tblReport.getTableHeader().setForeground(ColorsTheme.Text_White);
        
        scrollReport = new JScrollPane(tblReport);
        scrollReport.setBounds(0, 60, 1500, 900);
        pnlMiddle.add(scrollReport);
        
        lblHead = new JLabel("Generated Reports");
        lblHead.setBounds(30, 20, 300, 30);
        lblHead.setFont(FontsTheme.Title_Texts);
        lblHead.setForeground(ColorsTheme.Text_Black);
        pnlMiddle.add(lblHead);
         
        
        
        //ActionListener
        btnAdd.addActionListener(this);

       
        
        
    }
    
    public JPanel createCard(String title, String value, String subtitle, Color topLineColor) {

        cardPanel = new JPanel();
        cardPanel.setLayout(null);
        cardPanel.setBackground(ColorsTheme.Main_Card);
        
        TopPanel = new JPanel();
        TopPanel.setBounds(0, 0, 350, 10);
        TopPanel.setBackground(topLineColor);
        cardPanel.add(TopPanel);

        lblTitle = new JLabel(title);
        lblTitle.setBounds(20, 25, 250, 25);
        lblTitle.setForeground(ColorsTheme.Text_Black);
        lblTitle.setFont(FontsTheme.Plain_Texts);
        cardPanel.add(lblTitle);

        lblValue = new JLabel(value);
        lblValue.setBounds(20, 50, 200, 50);
        lblValue.setForeground(Color.BLACK);
        lblValue.setFont(FontsTheme.Bold_Texts);
        cardPanel.add(lblValue);

        lblSubtitle = new JLabel(subtitle);
        lblSubtitle.setBounds(20, 100, 250, 25);
        lblSubtitle.setForeground(Color.GRAY);
        lblSubtitle.setFont(FontsTheme.Plain_Texts);
        cardPanel.add(lblSubtitle);


        return cardPanel;
        
        
            }
    
    
    
    

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btnAdd) {
            NewReportDialog report = new NewReportDialog();
            report.setVisible(true);
        }
        
    }
    
}