/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package panels;


import constants.PanelCard2;
import constants.ColorsTheme;
import constants.FontsTheme;
import constants.TablePanel;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import dialogs.NewReportDialog;

/**
 *
 * 
 */
public class ReportsPanel extends JPanel implements ActionListener{
    
    private JPanel pnlMiddle, pnlPatient, pnlBilling, pnlLab, pnlPharmacy;
    private JLabel lblDetails, lblReports;
    private JButton btnAdd;
    private TablePanel tblReport;
    
    
    public ReportsPanel() {
        setLayout(null);
        setBackground(ColorsTheme.Middle_Panel);
        
        
        //Main Panel Container for Table
        pnlMiddle = new JPanel();
        pnlMiddle.setLayout(null);
        pnlMiddle.setBounds(70, 300, 1500, 500);
        pnlMiddle.setBackground(ColorsTheme.Main_Card);
        add(pnlMiddle);
        
        //Button for adding new appointment
        btnAdd = new JButton("+  Generate Report");
        btnAdd.setBounds(1280, 40, 250, 50); 
        btnAdd.setFont(FontsTheme.Buttons);
        btnAdd.setBackground(ColorsTheme.Add_Confirm);
        btnAdd.setForeground(ColorsTheme.Text_White);
        add(btnAdd);
        
        
        //Title and subtitle label for reports section
        lblReports = new JLabel("Reports");
        lblReports.setBounds(30, 30, 500, 40);
        lblReports.setFont(FontsTheme.Bold_Texts);
        lblReports.setForeground(ColorsTheme.Text_Black);
        add(lblReports);

        lblDetails = new JLabel("Generate and view hospital reports.");
        lblDetails.setBounds(30, 70, 500, 40);
        lblDetails.setFont(FontsTheme.Plain_Texts);
        lblDetails.setForeground(ColorsTheme.Text_Gray);
        add(lblDetails);
        
        
        //Summary Panel Cards
        pnlPatient = new PanelCard2("Patient Reports", "24", "Records Summary", ColorsTheme.Blue);
        pnlPatient.setBounds(70, 130, 350, 140);
        add(pnlPatient);
        
        pnlBilling = new PanelCard2("Billing Reports", "18", "Revenue and Invoices", ColorsTheme.Green);
        pnlBilling.setBounds(450, 130, 350, 140);
        add(pnlBilling);
       
        pnlLab = new PanelCard2("Lab Reports", "32", "Test Results", ColorsTheme.Red);
        pnlLab.setBounds(830, 130, 350, 140);
        add(pnlLab);
        
        pnlPharmacy = new PanelCard2("Pharmacy Reports", "15", "Inventory movement", ColorsTheme.Yellow);
        pnlPharmacy.setBounds(1210, 130, 350, 140);
        add(pnlPharmacy);
        
        
        
        
        //Table column names
        String[] columns = {"Report ID", "Report Name", "Type", "Generated By", "Date Generated", "Status", "Actions"};
        
        //Sample records
        Object[][] data = {
                
        };
        
        

        
        //Table Panel for records
        tblReport = new TablePanel("Generated Reports", columns, data, 940);
        tblReport.setBounds(0, 0, 1500, 560);
        pnlMiddle.add(tblReport);
        
        
        //ActionListener
        btnAdd.addActionListener(this);

       
        
        
    }
    
    
    
    

    @Override
    public void actionPerformed(ActionEvent e) {
        //Opens report form dialog
        if (e.getSource() == btnAdd) {
            NewReportDialog report = new NewReportDialog();
            report.setVisible(true);
        }
        
    }
    
}