/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.hospitalmanage;

import java.awt.Dialog;
import java.awt.Window;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author eiros
 */
public class NewreportDialog extends JDialog{
    
    NewreportDialog() {
        
        setLayout(null);
        setSize(800, 500);
        setLocationRelativeTo(null);
        getContentPane().setBackground(ColorsTheme.Middle_Panel);
        
        JLabel lblDialogTitle = new JLabel("Generate Report");
        lblDialogTitle.setBounds(40, 25, 350, 35);
        lblDialogTitle.setFont(FontsTheme.Bold_Texts);
        lblDialogTitle.setForeground(ColorsTheme.Text_Black);
        add(lblDialogTitle);
        
        JLabel lblDialogDetails = new JLabel("Choose the report type and date range");
        lblDialogDetails.setBounds(40, 60, 450, 30);
        lblDialogDetails.setFont(FontsTheme.Info_Texts);
        lblDialogDetails.setForeground(ColorsTheme.Text_Gray);
        add(lblDialogDetails);
        
        JLabel lblReportTitle = createFormLabel("Report Title:");
        lblReportTitle.setBounds(80, 115, 170, 30);
        add(lblReportTitle);
        
        JTextField txtReportTitle = createFormTextField();
        txtReportTitle.setBounds(260, 115, 350, 30);
        add(txtReportTitle);
        
        JLabel lblReportType = createFormLabel("Report Type:");
        lblReportType.setBounds(80, 160, 170, 30);
        add(lblReportType);
        
        JComboBox<String> cmbReportType = new JComboBox<>(new String[]{
                "Patient Report",
                "Billing Report",
                "Laboratory Report",
                "Pharmacy Report",
                "Bed Occupancy Report",
                "Emergency Report",
                "Appointment Report"
        });
        cmbReportType.setBounds(260, 160, 350, 30);
        cmbReportType.setFont(FontsTheme.Info_Texts);
        add(cmbReportType);
        
        JLabel lblDateFrom = createFormLabel("Date From:");
        lblDateFrom.setBounds(80, 205, 170, 30);
        add(lblDateFrom);
        
        JTextField txtDateFrom = createFormTextField();
        txtDateFrom.setBounds(260, 205, 180, 30);
        add(txtDateFrom);
        
        JLabel lblDateTo = createFormLabel("Date To:");
        lblDateTo.setBounds(80, 250, 170, 30);
        add(lblDateTo);
        
        JTextField txtDateTo = createFormTextField();
        txtDateTo.setBounds(260, 250, 180, 30);
        add(txtDateTo);
        
        JLabel lblGeneratedBy = createFormLabel("Generated By:");
        lblGeneratedBy.setBounds(80, 295, 170, 30);
        add(lblGeneratedBy);
        
        JTextField txtGeneratedBy = createFormTextField();
        txtGeneratedBy.setBounds(260, 295, 350, 30);
        add(txtGeneratedBy);
        
        JLabel lblNotes = createFormLabel("Notes:");
        lblNotes.setBounds(80, 340, 170, 30);
        add(lblNotes);
        
        JTextField txtNotes = createFormTextField();
        txtNotes.setBounds(260, 340, 350, 30);
        add(txtNotes);
        
        JButton btnCancel = new JButton("Cancel");
        btnCancel.setBounds(470, 390, 120, 40);
        btnCancel.setFont(FontsTheme.Buttons);
        btnCancel.setBackground(ColorsTheme.Text_Gray);
        btnCancel.setForeground(ColorsTheme.Text_White);
        btnCancel.addActionListener(e -> dispose());
        add(btnCancel);
        
        JButton btnGenerate = new JButton("Generate");
        btnGenerate.setBounds(610, 390, 150, 40);
        btnGenerate.setFont(FontsTheme.Buttons);
        btnGenerate.setBackground(ColorsTheme.Add_Confirm);
        btnGenerate.setForeground(ColorsTheme.Text_White);
        add(btnGenerate);
        
        setVisible(true);
    }
    
    private JLabel createFormLabel(String text) {
        JLabel label = new JLabel(text);
        label.setFont(FontsTheme.Plain_Texts);
        label.setForeground(ColorsTheme.Text_Black);
        return label;
    }
    
    private JTextField createFormTextField() {
        JTextField textField = new JTextField();
        textField.setFont(FontsTheme.Info_Texts);
        return textField;
    }
}
