/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.hospitalmanage;

import constants.ColorsTheme;
import constants.FontsTheme;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author eiros
 */
public class NewreportDialog extends JDialog implements ActionListener {
    
    private JButton btnReportDetails, btnFiltersNotes;
    private JPanel pnlReportDetails, pnlFiltersNotes;
    
    NewreportDialog() {
        
        setLayout(null);
        setSize(1050, 585);
        setLocationRelativeTo(null);
        getContentPane().setBackground(ColorsTheme.Middle_Panel);
        
        JLabel lblDialogIcon = createIconLabel("/icons/reports.png");
        lblDialogIcon.setBounds(40, 25, 56, 56);
        add(lblDialogIcon);

        JLabel lblDialogTitle = new JLabel("Generate Report");
        lblDialogTitle.setBounds(110, 25, 350, 35);
        lblDialogTitle.setFont(FontsTheme.Bold_Texts);
        lblDialogTitle.setForeground(ColorsTheme.Text_Black);
        add(lblDialogTitle);
        
        JLabel lblDialogDetails = new JLabel("Choose the report type and date range");
        lblDialogDetails.setBounds(110, 60, 450, 30);
        lblDialogDetails.setFont(FontsTheme.Info_Texts);
        lblDialogDetails.setForeground(ColorsTheme.Text_Gray);
        add(lblDialogDetails);

        btnReportDetails = createTabButton("Report Details");
        btnReportDetails.setBounds(50, 115, 250, 40);
        btnReportDetails.addActionListener(this);
        add(btnReportDetails);

        btnFiltersNotes = createTabButton("Filters/Notes");
        btnFiltersNotes.setBounds(300, 115, 250, 40);
        btnFiltersNotes.addActionListener(this);
        add(btnFiltersNotes);

        pnlReportDetails = createFormPanel();
        add(pnlReportDetails);

        pnlFiltersNotes = createFormPanel();
        pnlFiltersNotes.setVisible(false);
        add(pnlFiltersNotes);
        
        JLabel lblReportTitle = createFormLabel("Report Title:");
        lblReportTitle.setBounds(110, 35, 170, 30);
        pnlReportDetails.add(lblReportTitle);
        
        JTextField txtReportTitle = createFormTextField();
        txtReportTitle.setBounds(290, 35, 500, 30);
        pnlReportDetails.add(txtReportTitle);
        
        JLabel lblReportType = createFormLabel("Report Type:");
        lblReportType.setBounds(110, 80, 170, 30);
        pnlReportDetails.add(lblReportType);
        
        JComboBox<String> cmbReportType = new JComboBox<>(new String[]{
                "Patient Report",
                "Billing Report",
                "Laboratory Report",
                "Pharmacy Report",
                "Bed Occupancy Report",
                "Emergency Report",
                "Appointment Report"
        });
        cmbReportType.setBounds(290, 80, 500, 30);
        cmbReportType.setFont(FontsTheme.Info_Texts);
        pnlReportDetails.add(cmbReportType);
        
        JLabel lblGeneratedBy = createFormLabel("Generated By:");
        lblGeneratedBy.setBounds(110, 125, 170, 30);
        pnlReportDetails.add(lblGeneratedBy);
        
        JTextField txtGeneratedBy = createFormTextField();
        txtGeneratedBy.setBounds(290, 125, 500, 30);
        pnlReportDetails.add(txtGeneratedBy);

        JLabel lblDateFrom = createFormLabel("Date From:");
        lblDateFrom.setBounds(110, 35, 170, 30);
        pnlFiltersNotes.add(lblDateFrom);
        
        JTextField txtDateFrom = createFormTextField();
        txtDateFrom.setBounds(290, 35, 190, 30);
        pnlFiltersNotes.add(txtDateFrom);
        
        JLabel lblDateTo = createFormLabel("Date To:");
        lblDateTo.setBounds(520, 35, 110, 30);
        pnlFiltersNotes.add(lblDateTo);
        
        JTextField txtDateTo = createFormTextField();
        txtDateTo.setBounds(630, 35, 160, 30);
        pnlFiltersNotes.add(txtDateTo);

        JLabel lblNotes = createFormLabel("Notes:");
        lblNotes.setBounds(110, 95, 170, 30);
        pnlFiltersNotes.add(lblNotes);

        JTextArea txaNotes = new JTextArea("Write report notes here...");
        txaNotes.setFont(FontsTheme.Info_Texts);
        txaNotes.setForeground(ColorsTheme.Text_Gray);
        txaNotes.setLineWrap(true);
        txaNotes.setWrapStyleWord(true);

        JScrollPane scrollNotes = new JScrollPane(txaNotes);
        scrollNotes.setBounds(290, 95, 500, 160);
        pnlFiltersNotes.add(scrollNotes);

        JButton btnCancel = new JButton("Cancel");
        btnCancel.setBounds(700, 495, 120, 40);
        btnCancel.setFont(FontsTheme.Buttons);
        btnCancel.setBackground(ColorsTheme.Text_Gray);
        btnCancel.setForeground(ColorsTheme.Text_White);
        btnCancel.addActionListener(e -> dispose());
        add(btnCancel);

        JButton btnGenerate = new JButton("Generate");
        btnGenerate.setBounds(835, 495, 165, 40);
        btnGenerate.setFont(FontsTheme.Buttons);
        btnGenerate.setBackground(ColorsTheme.Add_Confirm);
        btnGenerate.setForeground(ColorsTheme.Text_White);
        add(btnGenerate);
        
        setVisible(true);
    }
    
    private JLabel createFormLabel(String text) {
        JLabel label = new JLabel(text);
        label.setFont(FontsTheme.Plain_Texts);
        label.setForeground(ColorsTheme.Text_Black);
        return label;
    }
    
    private JTextField createFormTextField() {
        JTextField textField = new JTextField();
        textField.setFont(FontsTheme.Info_Texts);
        return textField;
    }

    private JPanel createFormPanel() {
        JPanel panel = new JPanel();
        panel.setLayout(null);
        panel.setBounds(50, 155, 950, 325);
        panel.setBackground(ColorsTheme.Main_Card);
        return panel;
    }

    private JButton createTabButton(String text) {
        JButton button = new JButton(text);
        button.setFont(FontsTheme.Buttons);
        button.setBackground(ColorsTheme.Search_Button);
        button.setForeground(ColorsTheme.Text_White);
        button.setFocusPainted(false);
        return button;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btnReportDetails) {
            pnlReportDetails.setVisible(true);
            pnlFiltersNotes.setVisible(false);
        } else if (e.getSource() == btnFiltersNotes) {
            pnlReportDetails.setVisible(false);
            pnlFiltersNotes.setVisible(true);
        }
        
        revalidate();
        repaint();
    }

    private JLabel createIconLabel(String path) {
        java.net.URL resource = getClass().getResource(path);
        ImageIcon icon;
        
        if (resource != null) {
            icon = new ImageIcon(resource);
        } else {
            icon = new ImageIcon("src/main/resources" + path);
        }
        
        Image image = icon.getImage();
        Image scaledImage = image.getScaledInstance(56, 56, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        JLabel label = new JLabel(scaledIcon);
        
        return label;
    }
}
