/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.hospitalmanage;

import java.awt.Dialog;
import java.awt.Image;
import java.awt.Window;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author eiros
 */
public class NewreportDialog extends JDialog{
    
    NewreportDialog() {
        
        setLayout(null);
        setSize(1050, 585);
        setLocationRelativeTo(null);
        getContentPane().setBackground(ColorsTheme.Middle_Panel);
        
        JLabel lblDialogIcon = createIconLabel("/icons/reports.png");
        lblDialogIcon.setBounds(40, 25, 56, 56);
        add(lblDialogIcon);

        JLabel lblDialogTitle = new JLabel("Generate Report");
        lblDialogTitle.setBounds(110, 25, 350, 35);
        lblDialogTitle.setFont(FontsTheme.Bold_Texts);
        lblDialogTitle.setForeground(ColorsTheme.Text_Black);
        add(lblDialogTitle);
        
        JLabel lblDialogDetails = new JLabel("Choose the report type and date range");
        lblDialogDetails.setBounds(110, 60, 450, 30);
        lblDialogDetails.setFont(FontsTheme.Info_Texts);
        lblDialogDetails.setForeground(ColorsTheme.Text_Gray);
        add(lblDialogDetails);

        JPanel pnlForm = new JPanel();
        pnlForm.setLayout(null);
        pnlForm.setBounds(50, 115, 950, 365);
        pnlForm.setBackground(ColorsTheme.Main_Card);
        add(pnlForm);
        
        JLabel lblReportTitle = createFormLabel("Report Title:");
        lblReportTitle.setBounds(110, 35, 170, 30);
        pnlForm.add(lblReportTitle);
        
        JTextField txtReportTitle = createFormTextField();
        txtReportTitle.setBounds(290, 35, 500, 30);
        pnlForm.add(txtReportTitle);
        
        JLabel lblReportType = createFormLabel("Report Type:");
        lblReportType.setBounds(110, 80, 170, 30);
        pnlForm.add(lblReportType);
        
        JComboBox<String> cmbReportType = new JComboBox<>(new String[]{
                "Patient Report",
                "Billing Report",
                "Laboratory Report",
                "Pharmacy Report",
                "Bed Occupancy Report",
                "Emergency Report",
                "Appointment Report"
        });
        cmbReportType.setBounds(290, 80, 500, 30);
        cmbReportType.setFont(FontsTheme.Info_Texts);
        pnlForm.add(cmbReportType);
        
        JLabel lblDateFrom = createFormLabel("Date From:");
        lblDateFrom.setBounds(110, 125, 170, 30);
        pnlForm.add(lblDateFrom);
        
        JTextField txtDateFrom = createFormTextField();
        txtDateFrom.setBounds(290, 125, 190, 30);
        pnlForm.add(txtDateFrom);
        
        JLabel lblDateTo = createFormLabel("Date To:");
        lblDateTo.setBounds(520, 125, 110, 30);
        pnlForm.add(lblDateTo);
        
        JTextField txtDateTo = createFormTextField();
        txtDateTo.setBounds(630, 125, 160, 30);
        pnlForm.add(txtDateTo);
        
        JLabel lblGeneratedBy = createFormLabel("Generated By:");
        lblGeneratedBy.setBounds(110, 170, 170, 30);
        pnlForm.add(lblGeneratedBy);
        
        JTextField txtGeneratedBy = createFormTextField();
        txtGeneratedBy.setBounds(290, 170, 500, 30);
        pnlForm.add(txtGeneratedBy);

        JLabel lblNotes = createFormLabel("Notes:");
        lblNotes.setBounds(110, 220, 170, 30);
        pnlForm.add(lblNotes);

        JTextArea txaNotes = new JTextArea("Write report notes here...");
        txaNotes.setFont(FontsTheme.Info_Texts);
        txaNotes.setForeground(ColorsTheme.Text_Gray);
        txaNotes.setLineWrap(true);
        txaNotes.setWrapStyleWord(true);

        JScrollPane scrollNotes = new JScrollPane(txaNotes);
        scrollNotes.setBounds(290, 220, 500, 90);
        pnlForm.add(scrollNotes);
        
        JButton btnCancel = new JButton("Cancel");
        btnCancel.setBounds(700, 495, 120, 40);
        btnCancel.setFont(FontsTheme.Buttons);
        btnCancel.setBackground(ColorsTheme.Text_Gray);
        btnCancel.setForeground(ColorsTheme.Text_White);
        btnCancel.addActionListener(e -> dispose());
        add(btnCancel);

        JButton btnGenerate = new JButton("Generate");
        btnGenerate.setBounds(835, 495, 165, 40);
        btnGenerate.setFont(FontsTheme.Buttons);
        btnGenerate.setBackground(ColorsTheme.Add_Confirm);
        btnGenerate.setForeground(ColorsTheme.Text_White);
        add(btnGenerate);
        
        setVisible(true);
    }
    
    private JLabel createFormLabel(String text) {
        JLabel label = new JLabel(text);
        label.setFont(FontsTheme.Plain_Texts);
        label.setForeground(ColorsTheme.Text_Black);
        return label;
    }
    
    private JTextField createFormTextField() {
        JTextField textField = new JTextField();
        textField.setFont(FontsTheme.Info_Texts);
        return textField;
    }

    private JLabel createIconLabel(String path) {
        java.net.URL resource = getClass().getResource(path);
        ImageIcon icon = resource == null
                ? new ImageIcon("src/main/resources" + path)
                : new ImageIcon(resource);
        Image scaledImage = icon.getImage().getScaledInstance(56, 56, Image.SCALE_SMOOTH);
        return new JLabel(new ImageIcon(scaledImage));
    }
}
